library("org.Hs.eg.db")
KEGG.list<-as.list(org.Hs.egPATH)
GO.list<-as.list(org.Hs.egGO)
GO.list2<-list()
for(i in 1:length(GO.list))  GO.list2[[i]]<-names(GO.list[[i]])
rm(GO.list)
SYMBOL.list<-as.list(org.Hs.egSYMBOL)
names(KEGG.list)<-unlist(SYMBOL.list)
names(GO.list2)<-SYMBOL.list[1:length(GO.list2)]
path<-as.list(KEGGPATHID2NAME)
path2<-as.list(GOTERM)
pathx<-list()
for(i in 1:length(path2)) pathx[[i]]<-path2[[i]]@Term
names(pathx)<-names(path2)
rm(path2)
system("bash download_WikiPathways.sh")
  #source("download_WikiPathways.R")
load("WikiPathways.db.RData")
reactome.list<-as.list(reactomeEXTID2PATHID)
reactome.list<-reactome.list[match(names(SYMBOL.list), names(reactome.list))]
names(reactome.list)<-unlist(SYMBOL.list)
path4<-as.list(reactomePATHID2NAME)
path4<-lapply(path4[grep("Homo sapiens", path4)], function(x) strsplit(x, split=": ")[[1]][2:length(strsplit(x, split=": ")[[1]])])
load("Gene_Set_Data.RData")